name: Track and Sync Upstream Commits

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0  # Needed for full history

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add and fetch upstream
        run: |
          git remote add upstream https://github.com/otavioschwanck/arrow.nvim.git
          git fetch upstream

      - name: Create new branch for sync
        run: |
          git checkout -b upstream-sync

      - name: Cherry-pick new commits
        run: |
          # Find commits in upstream/master not in origin/master
          COMMITS=$(git log master..upstream/master --oneline --reverse | awk '{print $1}')
          echo "Found upstream commits: $COMMITS"

          for COMMIT in $COMMITS; do
            echo "Cherry-picking $COMMIT"
            git cherry-pick $COMMIT || {
              echo "Conflict on $COMMIT, aborting cherry-pick"
              git cherry-pick --abort
              break
            }
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Cherry-picked upstream commits"
          title: "Sync from upstream (cherry-picked)"
          body: |
            This PR includes cherry-picked commits from `otavioschwanck/arrow.nvim`.

            Review and resolve any conflicts if necessary.
          base: master
          branch: upstream-sync
          delete-branch: true
